import React from 'react';
import { X, Target, Brush, Bot, AlertTriangle } from 'lucide-react';

export default function HelpModal({ onClose }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
       <div className="absolute inset-0 bg-slate-900/40 backdrop-blur-sm" onClick={onClose}></div>
       <div className="relative bg-white rounded-2xl shadow-xl w-full max-w-2xl overflow-hidden flex flex-col max-h-[90vh] animate-in fade-in zoom-in-95 duration-300">
           
           <div className="p-6 border-b border-slate-100 flex items-center justify-between bg-slate-50">
               <h2 className="text-xl font-bold flex items-center gap-2 text-slate-800">
                   <Target className="text-primary-500" /> Let's get started with CleanIQ
               </h2>
               <button onClick={onClose} className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-200 rounded-lg transition-colors">
                   <X size={20} />
               </button>
           </div>
           
           <div className="p-6 overflow-y-auto flex-1 text-slate-600 space-y-6">
               <p className="text-lg">Welcome to CleanIQ, the Multi-Modal AI Data Quality Platform designed for precision.</p>
               
               <div className="bg-primary-50 border border-primary-100 p-4 rounded-xl">
                   <h3 className="font-bold text-primary-800 flex items-center gap-2 mb-2"><Target size={18} /> Data Quality Score (DQS)</h3>
                   <p className="text-sm text-primary-700">The DQS (out of 100) is a weighted, composite heuristic generated by our Core Profiling Engine. It tracks the consistency, validity, uniqueness, and completeness of your dataset based on mathematical anomaly detection algorithms.</p>
               </div>
               
               <div className="space-y-4 pt-2">
                   <h3 className="font-bold text-slate-800 border-b pb-2">Key Features</h3>
                   
                   <div className="flex items-start gap-4">
                       <div className="p-2 bg-slate-100 rounded-lg text-slate-700 shrink-0"><AlertTriangle size={20} /></div>
                       <div>
                           <h4 className="font-semibold text-slate-800">Automated Profiling</h4>
                           <p className="text-sm mt-1">Simply upload a CSV, Excel file, or a ZIP of images. CleanIQ scans for missing values, statistical outliers, duplicated rows/images, blurriness, and structural corruption.</p>
                       </div>
                   </div>
                   
                   <div className="flex items-start gap-4">
                       <div className="p-2 bg-slate-100 rounded-lg text-slate-700 shrink-0"><Bot size={20} /></div>
                       <div>
                           <h4 className="font-semibold text-slate-800">CleanIQ Assistant</h4>
                           <p className="text-sm mt-1">Driven by Groq and Llama 3, the Chat Assistant understands the live context of your uploaded dataset. Ask it to explain what an outlier means, or why certain columns exhibit missing data shapes.</p>
                       </div>
                   </div>
                   
                   <div className="flex items-start gap-4">
                       <div className="p-2 bg-slate-100 rounded-lg text-slate-700 shrink-0"><Brush size={20} /></div>
                       <div>
                           <h4 className="font-semibold text-slate-800">Action Center</h4>
                           <p className="text-sm mt-1">Experience one-click data fixes. Instruct the engine to purge missing data or use contextual "Smart Fixes" to impute median values. Watch your DQS score improve alongside these fixes!</p>
                       </div>
                   </div>
               </div>
           </div>
           
           <div className="p-6 border-t border-slate-100 flex justify-end bg-white">
               <button onClick={onClose} className="px-6 py-2 bg-slate-800 text-white rounded-lg hover:bg-slate-700 font-medium transition-colors shadow-sm">
                   Got it
               </button>
           </div>
       </div>
    </div>
  );
}
